config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :jobs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "jobs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user

  validates :user, :protocol, :address_zipcode, :address, :address_number, :starts_at, :ends_at, :description, presence: true
  validates :description, length: { maximum: 1000 }

  def full_address
    [address_zipcode, address, address_number].join(', ')
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :phone, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, uniqueness: true
  def identify
    "#{name} - #{email}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.paginate(:page => params[:page])
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to jobs_path, notice: 'Chamado foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to jobs_path, notice: 'Chamado foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Chamado foi removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:user_id, :protocol, :address_zipcode, :address, :address_number, :address_complement, :starts_at, :ends_at, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(:page => params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'Responsável foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'Responsável por atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Responsável foi removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h5><%= job.errors.count %> erro(s) foram encontrados:</h5>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= form.label :user_id %>
    <div>
    <%= form.collection_select :user_id, User.order(:name), :id, :identify, {:prompt=>true}, {class: 'custom-select'} %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :protocol %>
    <%= form.text_field :protocol, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :address_zipcode %>
    <%= form.text_field :address_zipcode, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :address_number %>
    <%= form.text_field :address_number, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :address_complement %>
    <%= form.text_field :address_complement, class: 'form-control' %>
  </div>

  <div class="form-group form-dates">
    <div>
      <%= form.label :starts_at %>
    </div>
    <%= form.date_select :starts_at, {}, {class: 'custom-select'} %>
  </div>

  <div class="form-group form-dates">
    <div>
    <%= form.label :ends_at %>
    </div>
    <%= form.date_select :ends_at, {}, {class: 'custom-select'} %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', rows: 10 %>
  </div>

  <div class="btn-group" role="group" aria-label="Ações">
    <%= form.submit 'Salvar', class: 'btn btn-primary active' %>
    <%= link_to 'Voltar para lista', jobs_path, class: 'btn btn-primary'  %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Alterando Chamado</h1>

<%= render 'form', job: @job %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="bs-docs-section">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-header">
        <h3 id="tables">Chamados</h3>
      </div>

      <div class="bs-component">
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">Responsável</th>
              <th scope="col">Protocolo</th>
              <th scope="col">Endereço</th>
              <th scope="col">Início</th>
              <th scope="col">Término</th>
              <th scope="col">Ações</th>
            </tr>
          </thead>

          <tbody>
            <% @jobs.each do |job| %>
              <tr>
                <td><%= job.user.identify %></td>
                <td><%= job.protocol %></td>
                <td><%= job.full_address %></td>
                <td><%= l job.starts_at %></td>
                <td><%= l job.ends_at %></td>
                <td>
                  <div class="btn-group" role="group" aria-label="Ações">
                    <%= link_to 'Editar', edit_job_path(job), class: 'btn btn-primary btn-sm' %>
                    <%= link_to 'Apagar', job, method: :delete, data: { confirm: 'Deseja realmente remover este dado?' }, class: 'btn btn-danger btn-sm' %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<br>

<%= link_to 'Criar chamado', new_job_path, class: 'btn btn-primary' %>

app/views/jobs/new.html.erb
<h3>Criar Chamado</h3>

<%= render 'form', job: @job %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @job.user %>
</p>

<p>
  <strong>Protocol:</strong>
  <%= @job.protocol %>
</p>

<p>
  <strong>Address zipcode:</strong>
  <%= @job.address_zipcode %>
</p>

<p>
  <strong>Address:</strong>
  <%= @job.address %>
</p>

<p>
  <strong>Address number:</strong>
  <%= @job.address_number %>
</p>

<p>
  <strong>Address complement:</strong>
  <%= @job.address_complement %>
</p>

<p>
  <strong>Starts at:</strong>
  <%= @job.starts_at %>
</p>

<p>
  <strong>Ends at:</strong>
  <%= @job.ends_at %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Painel de Chamados Osasco</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script> -->

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Painel de Chamados <span class="caret"></span></a>
              <div class="dropdown-menu" aria-labelledby="themes">
                <%= link_to 'Lista de Chamados', jobs_path, class: 'dropdown-item' %>
                <%= link_to 'Crie um Chamado', new_job_path, class: 'dropdown-item' %>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">Responsáveis <span class="caret"></span></a>
              <div class="dropdown-menu" aria-labelledby="themes">
                <%= link_to 'Lista de Responsáveis', users_path, class: 'dropdown-item' %>
                <%= link_to 'Crie um Responsável', new_user_path, class: 'dropdown-item' %>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Central de ajuda</a>
            </li>
          </ul>

        </div>
      </div>
    </div>
    <div class="container">
      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-8 col-md-7 col-sm-6 justify-content-center align-self-center">
            <h1>Painel de Chamados</h1>
            <p class="lead">O controle rápido e fácil de seus chamados</p>
          </div>
          <div class="col-lg-4 col-md-5 col-sm-6 text-right">
            <div class="sponsor">
              <!-- <script async type="text/javascript" src="//cdn.carbonads.com/carbon.js?serve=CKYIE23N&placement=bootswatchcom" id="_carbonads_js"></script> -->
              <%= image_tag 'logo.png' %>
            </div>
          </div>
        </div>
      </div>
      <%= yield %>
      <footer id="footer">
        <div class="row">
          <div class="col-lg-12">

            <ul class="list-unstyled">
              <li class="float-lg-right"><a href="#top">Voltar para início</a></li>
            </ul>
            <p>Construído por <a href="https://proxer.com.br" target="_blank">proxer.com.br</a></p>
            <p>Versão 0.1</p>
          </div>
        </div>

      </footer>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h5><%= user.errors.count %> erro(s) foram encontrados:</h5>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: 'form-control' %>
  </div>

  <div class="btn-group" role="group" aria-label="Ações">
    <%= form.submit 'Salvar', class: 'btn btn-primary active' %>
    <%= link_to 'Voltar para lista', users_path, class: 'btn btn-primary'  %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h3>Editando Responsável</h3>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="bs-docs-section">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-header">
        <h3 id="tables">Responsáveis</h3>
      </div>

      <div class="bs-component">
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">Nome</th>
              <th scope="col">Email</th>
              <th scope="col">Telefone</th>
              <th scope="col">Ações</th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= user.phone %></td>
                <td>
                  <div class="btn-group" role="group" aria-label="Ações">
                    <%= link_to 'Editar', edit_user_path(user), class: 'btn btn-primary btn-sm' %>
                    <%= link_to 'Apagar', user, method: :delete, data: { confirm: 'Deseja realmente remover este dado?' }, class: 'btn btn-danger btn-sm' %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<br>

<%= link_to 'Criar responsável', new_user_path, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<h3>Criar Responsável</h3>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>